### PR TITLE
Increase the loading wheel size.

### PR DESCRIPTION
**Pull request by higorspinto**
- bring Upload component from datapub to increase the size of the loading wheel
- bring Progress Bar component from datapub to increase the size of the loading wheel text

Client's board [issue](https://gitlab.com/datopian/clients/nhsbsa-opendata-pm-shared/-/issues/104)

### CODE REVIEW

**Comment by higorspinto** [comment]
@kmanaseryan could you review this?

cc @mbeilin

**Review by kmanaseryan — COMMENTED** [review]
@higorspinto can we create a separate PR which will only include the new files from the core datapub repo? So after merging that first it will be easy to understand what are the main changes here related to the issue. If you do that today I can quickly review👍

**Comment by higorspinto** [comment]
Hey @kmanaseryan, I opened another PR to copy the components from `datapub` without any changes.

https://github.com/datopian/datapub-nhs/pull/16

I'll wait for the merge and then raise another PR with the changes I need. Sounds good?

**Comment by kmanaseryan** [comment]
@higorspinto wonderful, thank you! On it now.

**Comment by kmanaseryan** [comment]
@higorspinto I think now if you resolve the conflicts in this branch, then your changes for the issue will appear.

**Comment by higorspinto** [comment]
@kmanaseryan yes, it's ready for review. Let me know if you have any problems.

**Review by kmanaseryan — APPROVED** [review]
LGTM

**Pull request merged**
